<?php
/**
 * Title: Theme options
 *
 * Description: Defines fields for theme options.
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

function cyberchimps_add_core_headings( $headings_list ) {

	$headings_list = array();

	$headings_list[] = array(
		'id'    => 'cyberchimps_help_heading',
		'title' => __( 'Help', 'cyberchimps_core' ),
	);

	$headings_list[] = array(
		'id'    => 'cyberchimps_design_heading',
		'title' => __( 'Design', 'cyberchimps_core' ),
	);

	$headings_list[] = array(
		'id'    => 'cyberchimps_header_heading',
		'title' => __( 'Header', 'cyberchimps_core' ),
	);

	$headings_list[] = array(
		'id'    => 'cyberchimps_blog_heading',
		'title' => __( 'Blog', 'cyberchimps_core' ),
	);

	$headings_list[] = array(
		'id'    => 'cyberchimps_templates_heading',
		'title' => __( 'Templates', 'cyberchimps_core' ),
	);

	$headings_list[] = array(
		'id'    => 'cyberchimps_footer_heading',
		'title' => __( 'Footer', 'cyberchimps_core' ),
	);

	return apply_filters( 'cyberchimps_headings_filter', $headings_list );
}

add_filter( 'cyberchimps_heading_list', 'cyberchimps_add_core_headings' );

/**************************************************************************************/
/*************************** SUBSECTIONS **********************************************/
/**************************************************************************************/
function cyberchimps_add_core_sections( $sections_list ) {

	//theme check
	$theme_check = cyberchimps_theme_check();

	$sections_list = array();

	/*************************** WELCOME **************************************************/

	$sections_list[] = array(
		'id'      => 'cyberchimps_help_section',
		'label'   => apply_filters( 'cyberchimps_help_heading', 'CyberChimps' ),
		'heading' => 'cyberchimps_help_heading'
	);

	/**************************** DESIGN **************************************************/

	$sections_list[] = array(
		'id'      => 'cyberchimps_custom_layout_section',
		'label'   => __( 'Layout Options', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_design_heading'
	);

	/** COMMENTED OUT - Using WP background customization
	 * $sections_list[] = array(
	 * 'id' => 'cyberchimps_custom_background_section',
	 * 'label' => __('Background Options', 'cyberchimps_core' ),
	 * 'heading' => 'cyberchimps_design_heading'
	 * );
	 */

	$sections_list[] = array(
		'id'      => 'cyberchimps_custom_colors_section',
		'label'   => __( 'Custom Colors', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_design_heading'
	);

	$sections_list[] = array(
		'id'      => 'cyberchimps_typography_section',
		'label'   => __( 'Typography', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_design_heading'
	);

	/*$sections_list[] = array(
		'id' => 'cyberchimps_custom_css_section',
		'label' => __('Custom CSS', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_design_heading'
	);

/**************************** HEADER **************************************************/

	$sections_list[] = array(
		'id'      => 'cyberchimps_header_drag_drop_section',
		'label'   => __( 'Header Drag &#38; Drop', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_header_heading'
	);

	$sections_list[] = array(
		'id'      => 'cyberchimps_header_options_section',
		'label'   => __( 'Header Options', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_header_heading'
	);

	$sections_list[] = array(
		'id'      => 'cyberchimps_header_social_section',
		'label'   => __( 'Social Icons', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_header_heading'
	);
        $sections_list[] = array(
		'id'      => 'cyberchimps_header_contact_element',
		'label'   => __( 'Contact Element', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_header_heading'
	);

	/***************************** BLOG **************************************************/

	$sections_list[] = array(
		'id'      => 'cyberchimps_drag_and_drop_section',
		'label'   => __( 'Drag & Drop', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_blog_heading'
	);

	$sections_list[] = array(
		'id'      => 'cyberchimps_blog_options_section',
		'label'   => __( 'Blog Options', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_blog_heading'
	);

//check if free theme
	if ( $theme_check == 'free' ):
		$sections_list[] = array(
			'id'      => 'cyberchimps_blog_slider_lite_section',
			'label'   => __( 'Blog Slider Lite', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);

		$sections_list[] = array(
			'id'      => 'cyberchimps_blog_portfolio_lite_section',
			'label'   => __( 'Portfolio Lite Options', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);

		$sections_list[] = array(
			'id'      => 'cyberchimps_blog_boxes_lite_section',
			'label'   => __( 'Boxes Lite', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);
                $sections_list[] = array(
			'id'      => 'cyberchimps_testimonial_section',
			'label'   => __( 'Testimonial Options', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);
                 $sections_list[] = array(
			'id'      => 'cyberchimps_map_contact_section',
			'label'   => __( 'Contact Us Options', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);

	endif;

//check if pro theme
	if ( $theme_check == 'pro' ):
		$sections_list[] = array(
			'id'      => 'cyberchimps_slider_section',
			'label'   => __( 'Blog Slider', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);

		$sections_list[] = array(
			'id'      => 'cyberchimps_callout_section',
			'label'   => __( 'Callout Options', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);

		$sections_list[] = array(
			'id'      => 'cyberchimps_html_box_section',
			'label'   => __( 'HTML Box Options', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);

		$sections_list[] = array(
			'id'      => 'cyberchimps_carousel_section',
			'label'   => __( 'Carousel Options', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);

		$sections_list[] = array(
			'id'      => 'cyberchimps_portfolio_pro_section',
			'label'   => __( 'Portfolio Pro Options', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);

		$sections_list[] = array(
			'id'      => 'cyberchimps_recent_posts_section',
			'label'   => __( 'Recent Posts Options', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);
		$sections_list[] = array(
			'id'      => 'cyberchimps_separator_section',
			'label'   => __( 'Separator', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);
		$sections_list[] = array(
			'id'      => 'cyberchimps_blank_space_section',
			'label'   => __( 'Blank Space', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);
		$sections_list[] = array(
			'id'      => 'cyberchimps_google_maps_section',
			'label'   => __( 'Google Maps', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);
		$sections_list[] = array(
			'id'      => 'cyberchimps_video_section',
			'label'   => __( 'Video Options', 'cyberchimps_core' ),
			'heading' => 'cyberchimps_blog_heading'
		);
	endif;

	$sections_list[] = array(
		'id'      => 'cyberchimps_boxes_section',
		'label'   => __( 'Boxes Options', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_blog_heading'
	);

	/*$sections_list[] = array(
		'id' => 'cyberchimps_featured_posts_section',
		'label' => __('Featured Posts Options', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_blog_heading'
	);*/

	/*$sections_list[] = array(
		'id'		=> 'cyberchimps_profile_section',
		'label'		=> __('Profile Options', 'cyberchimps_core' ),
		'heading'	=> 'cyberchimps_blog_heading'
	);*/

	/*************************** TEMPLATE ************************************************/

	$sections_list[] = array(
		'id'      => 'cyberchimps_single_post_section',
		'label'   => __( 'Single Post', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_templates_heading'
	);

	$sections_list[] = array(
		'id'      => 'cyberchimps_archive_section',
		'label'   => __( 'Archive', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_templates_heading'
	);

	$sections_list[] = array(
		'id'      => 'cyberchimps_search_section',
		'label'   => __( 'Search', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_templates_heading'
	);

	$sections_list[] = array(
		'id'      => 'cyberchimps_error_section',
		'label'   => '404',
		'heading' => 'cyberchimps_templates_heading'
	);

	/**************************** FOOTER **************************************************/

	$sections_list[] = array(
		'id'      => 'cyberchimps_footer_section',
		'label'   => __( 'Footer Options', 'cyberchimps_core' ),
		'heading' => 'cyberchimps_footer_heading'
	);

	return apply_filters( 'cyberchimps_sections_filter', $sections_list );
}

add_filter( 'cyberchimps_section_list', 'cyberchimps_add_core_sections' );